name: SimpleLogin
main: SimpleLogin.Main
version: "1.0.3"
author: maru
api: ["1.0.0"]

permissions:
 simplelogin.*:
  default: true
  children:
   simplelogin.commands.*:
    default: true
    children:
     simplelogin.commands.login:
      default: true
     simplelogin.commands.register:
      default: true
     simplelogin.commands.manage:
      default: OP